happypets/app/urls.py
from django.urls import path, include 
from .views import home, productos, contacto, comentarios, blog, agregar_producto, listar_productos, modificar_producto, eliminar_producto, registro, ProductoViewset, agregar_mascota, listar_mascota, modificar_mascota, eliminar_mascota, MascotaViewset
from rest_framework import routers

### ACUERDATE DE GUARDAR AQUI, EL PROGRAMA NO ESTA AVISANDO CUANDO NO GUARDAS AQUI Y ESTO NO PERMITE QUE SE EJECUTEN LOS VIEWS.


router = routers.DefaultRouter()
router.register('producto', ProductoViewset)
router.register('mascota', MascotaViewset)


urlpatterns = [
    path('', home, name="home"),
    path('productos/', productos, name="productos"),
    path('contacto/', contacto, name="contacto"),
    path('comentarios/', comentarios, name="comentarios"),
    path('blog/', blog, name="blog"),
    path('agregar-producto/', agregar_producto, name="agregar_producto"),
    path('agregar-mascota/', agregar_mascota, name="agregar_mascota"),
    path('listar-productos/', listar_productos, name="listar_productos"),
    path('listar-mascota/', listar_mascota, name="listar_mascota"),
    path('modificar-producto/<id>/', modificar_producto, name="modificar_productos"),
    path('modificar-mascota/<id>/', modificar_mascota, name="modificar_mascota"),
    path('eliminar-producto/<id>/', eliminar_producto, name="eliminar_producto"),
    path('eliminar-mascota/<id>/', eliminar_mascota, name="eliminar_mascota"),
    path('registro/', registro, name="registro"),
    path('api/', include(router.urls)),




]

happypets/happypets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

happypets/app/models.py
from django.db import models

# Create your models here.

class Producto(models.Model):
    nombre = models.CharField(max_length = 50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    fecha_duracion = models.DateField()

    def __str__(self):
        return self.nombre, self.precio, self.descripcion, self.fecha_duracion

    
class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    correo = models.EmailField()
    telefono = models.CharField(max_length=9)

    def __str__(self):
        return self.nombre, self.apellido, self.correo, self.telefono


class Mascota(models.Model):
    especie = models.CharField(max_length = 50)
    nombre = models.CharField(max_length = 50)
    descripcion = models.TextField()
    fecha_rescate = models.DateField()

    def __str__(self):
        return self.especie, self.nombre, self.descripcion, self.fecha_rescate

happypets/app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Happy Pets</title>
    <!-- FONTELLO ES UNA PAGINA QUE OFRECE ICONOS BASICOS -->
    <!-- SOLO SE DESCARGAN Y SE AGREGAN AL PROYECTO Y LUEGO SE LINKEAN -->
    {% load static %}

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    {% block css %}

    {% endblock %}

    <link rel="stylesheet" href="{% static 'app/css/fontello.css' %}">
    <link rel="stylesheet" href= "{% static 'app/css/estilos.css' %}">
</head>
<body>
    <header>
        <div class="Contenedor">
            <h1 class="icon-won">Happy Pets</h1>
            <input type="checkbox" id="menu-bar">
            <label class="icon-menu" for="menu-bar"></label>
            <nav class="menu">
                <a href="{% url 'home' %}">Inicio</a>
                <a href="{% url 'productos' %}">Productos</a>
                <a href="{% url 'blog' %}">Blog</a>
                <!-- <a href="{% url 'contacto' %}">Contacto</a> -->

                {% if perms.app.add_producto %}
                
                <a href="{% url 'agregar_producto' %}">Agregar Oferta</a>

                <a href="{% url 'agregar_mascota' %}">Agregar Mascota</a>

                {% endif %}

                <!-- <a href="{% url 'listar_productos' %}">Ofertas</a>  -->
                
                {% if user.is_authenticated %}

                <a href="{% url 'contacto' %}">Contacto</a>

                <a href="{% url 'listar_productos' %}">Ofertas</a>

                <a href="{% url 'listar_mascota' %}">Mascotas</a>

                <a href="{% url 'logout' %}">Cerrar session</a>

                <a href="{% url 'home' %}">@{{ user.username }}</a>


                {% else %}

                <a href="{% url 'login' %}">Iniciar session</a>

                <a href="{% url 'registro' %}">Registrarse</a>

                {% endif %}
            </nav>
        </div>
    </header>

    <main>
        <section id="banner">
            <img src="{% static 'app/img/Perro_pagina_principal.jpg' %}">
            <div class="contenedor">
               <h2>Las Mascotas son amor para nuestras vidas</h2>
               <p>¿Y tu, que esperas encontrar la tu ya?</p>
               <a href="{% url 'comentarios' %}">Refugio</a>
            </div>
        </section>



        {% block contenido %}



        {% endblock %}



    </main>

    <footer>
        <div class="contenedor">
            <p class="copy">Happy pets &copy; 2022</p>
            <div class="sociales">
                <a class="icon-facebook"href="#!"></a>
                <a class="icon-twitter" href="#!"></a>
                <a class="icon-instagram" href="#!"></a>
            </div>
        </div>
    </footer>

    {% block js %}

    {% endblock %}

</body>
</html>

happypets/app/templates/app/blog.html
{% extends 'app/base.html' %}

{% load static %}

{% block js %}
{% endblock %}

{% block css %}
{% endblock %}

{% block contenido %}

<section id="Bienvenidos">
    <h2>HAPPY PETS QUE HOY TIENEN FAMILIA</h2>
    <p>Estos son algunos happy pets que hemos logrado ayudar gracias a las ventas de la tienda</p>
</section>
<section id="blog">
    <h3></h3>
    <div class="contenedor">
        <article>
            <img src="{% static 'app/img/BLOG/blog_grande1.jpg' %}">
            <h4>Max junto a su nueva compañera</h4>
        </article>
        <article>
            <img src="{% static 'app/img/BLOG/blog_grande2.jpg' %}">
            <h4>El pequeño tomy junto a su nueva amiga</h4>
        </article>
        <article>
            <img src="{% static 'app/img/BLOG/blog_grande3.jpg' %}">
            <h4>El gran terry junto a su nueva familia</h4>
        </article>
    </div>
</section>

<section id="info">
    <h3>FELICES HAPPY PETS</h3>
    <div class="contenedor">
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo1.jpg' %}" alt="">
            <h4>Los hermanos tom y luna con sus nuevos amigos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo2.jpg' %}" alt="">
            <h4>El serio luis con sus nuevos amigos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo3.jpg' %}" alt="">
            <h4>Chop encontro a su nuevo compañero</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo4.jpg' %}" alt="">
            <h4>Kira encontro a su nueva mejor amiga</h4>
        </div>

    </div>

</section>

{% endblock %}

happypets/app/templates/app/comentarios.html
{% extends 'app/base.html' %}

{% load static %}

{% block js %}
<script src="app/js/map.js"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
crossorigin="anonymous"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}

{% block css %}
{% endblock %}

{% block contenido %}
<section id="Bienvenidos">
    <h2>MANTENTE INFORMADO DE LO QUE SUCEDE EN HAPPY PETS</h2>
    <p>Aqui se encuentra ubicado el refugio al cual estamos asociados y brindamos apoyo</p>
</section>
<section id="comentarios">
    <div class="col-10 col-md-8 offset-md-4">
    <h5>Ubicacion del refugio asociado</h5>
    </div>
    <div class="contenedor">
        <div class="col-10 col-md-8 offset-md-4">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3329.077690870305!2d-70.65978848487063!3d-33.44728238077488!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662c507f91be917%3A0xcfac72a68dd4b986!2sDuoc%20UC%20-%20Sede%20Padre%20Alonso%20de%20Ovalle!5e0!3m2!1ses!2scl!4v1649350072384!5m2!1ses!2scl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>   
        </div>
    </div>
</section>

<section id="info">
    <h3>FELICES HAPPY PETS</h3>
    <div class="contenedor">
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo1.jpg' %}" alt="">
            <h4>Los hermanos tom y luna con sus nuevos amigos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo2.jpg' %}" alt="">
            <h4>El serio luis con sus nuevos amigos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo3.jpg' %}" alt="">
            <h4>Chop encontro a su nuevo compañero</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo4.jpg' %}" alt="">
            <h4>Kira encontro a su nueva mejor amiga</h4>
        </div>

    </div>

</section>
{% endblock %}

happypets/app/templates/app/contacto.html
{% extends 'app/base.html' %}

{% load static %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.min.js"></script>
<script src="js/traducciones_jquery.js"></script>
<script src="js/formulario_jquery.js"></script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href= "{% static 'app/css/estilos.css' %}">
{% endblock %}


{% block contenido %}

<section id="Bienvenidos">
    <h2>MANTENTE INFORMADO DE LO QUE SUCEDE EN HAPPY PETS</h2>
    <p>Rellena este formulario para poder recibir informacion de nuevos productos y de happy pets que neseciten ayuda</p>
</section>

<div class="row">
    
    <div class="col-10 col-md-10 offset-md-1">
        <div class="card">
            <div class="card-body">
                <h5>Formulario Contacto</h5>
        
                <form action="" id="formulario_contacto", method="post">
        
                    {% csrf_token %}
                 
                    {{ form }}

                    <br>
                    <br>
                    <br>
                    <button class="botones" type="submit" id="guardar">Guardar</button>
                </form>

            </div>
            
        </div>

    </div>
</div>
<br>
<br>


<section id="info">
    <h3>FELICES HAPPY PETS</h3>
    <div class="contenedor">
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo1.jpg' %}" alt="">
            <h4>Los hermanos tom y luna con sus nuevos amigos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo2.jpg' %}" alt="">
            <h4>El serio luis con sus nuevos amigos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo3.jpg' %}" alt="">
            <h4>Chop encontro a su nuevo compañero</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo4.jpg' %}" alt="">
            <h4>Kira encontro a su nueva mejor amiga</h4>
        </div>

    </div>

</section>

{% endblock %}

happypets/app/templates/app/home.html
{% extends 'app/base.html' %}

{% load static %}

{% block js %}
{% endblock %}

{% block css %}
{% endblock %}

{% block contenido %}
</section>
<section id="Bienvenidos">
    <h2>BIENVENIDOS A HAPPY PETS</h2>
    <p>Happy Pets es una tienda de productos para mascotas que apoya a una fundacion de ayuda a los animales nesecitados sin fines de lucro.</p>
</section>
<section id="blog">
    <h3>Lo ultimo de nuestro blog</h3>
    <div class="contenedor">
        <article>
            <img src="{% static 'app/img/INICIO/blog_img1.jpg' %}">
            <h4>Tomy fue un rescatadon, hoy esta con una familia amorosa</h4>
        </article>
        <article>
            <img src="{% static 'app/img/INICIO/blog_img2.jpg' %}">
            <h4>Julieta en su nueva familia que la ama</h4>
        </article>
        <article>
            <img src="{% static 'app/img/INICIO/blog_img3.jpg' %}">
            <h4>Rex junto a su nuevo amigo en su nueva casa</h4>
        </article>
    </div>
</section>

<section id="info">
    <h3>Para nosotros la calidad en los productos que usamos es importante para entregarte el mejor servicio</h3>
    <div class="contenedor">
        <div class="info-productos">
            <img src="{% static 'app/img/INICIO/info_inicio1.jpg' %}" alt="">
            <h4>Peto para perros de estura media lineas rojas</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/INICIO/info_inicio2.jpg' %}" alt="">
            <h4>Corea para gatos celeste</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/INICIO/info_inicio3.jpg' %}" alt="">
            <h4>Correa para perros de estatura media color reflex </h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/INICIO/info_inicio4.jpg' %}" alt="">
            <h4>Petos caparazon de tortuga para gatos</h4>
        </div>

    </div>

</section>
{% endblock %}

happypets/app/templates/app/productos.html
{% extends 'app/base.html' %}

{% load static %}

{% block js %}
{% endblock %}

{% block css %}
{% endblock %}

{% block contenido %}

<section id="Bienvenidos">
    <h2>PRODUCTOS HAPPY PETS</h2>
    <p>Los productos de Happy pets estan hechos para brindar la mayor comodidad y felicidad a sus mascotas</p>
</section>
<section id="blog">
    <h3>Lo ultimo de nuestros productos</h3>
    <div class="contenedor">
        <article>
            <img src="{% static 'app/img/PRODUCTOS/producto_grande1.jpg' %}">
            <h4>Correa diseño de rosas para perro</h4>
        </article>
        <article>
            <img src="{% static 'app/img/PRODUCTOS/producto_grande2.jpg' %}">
            <h4>Collar cuero para gato</h4>
        </article>
        <article>
            <img src="{% static 'app/img/PRODUCTOS/producto_grande3.jpg' %}">
            <h4>Arnes negro para perro pequeño</h4>
        </article>
    </div>
</section>

<section id="info">
    <h3>Para nosotros la calidad en los productos que usamos es importante para entregarte el mejor servicio</h3>
    <div class="contenedor">
        <div class="info-productos">
            <img src="{% static 'app/img/PRODUCTOS/producto_abajo1.jpg' %}" alt="">
            <h4>Correa de cuero para gatos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/PRODUCTOS/producto_abajo2.jpe' %}g" alt="">
            <h4>Peto para gatos dos colores</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/PRODUCTOS/producto_abajo3.jpg' %}" alt="">
            <h4>Mordedor diseño hueso para perros</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/PRODUCTOS/producto_abajo4.jpg' %}" alt="">
            <h4>Collar de cuero para perro mediano</h4>
        </div>

    </div>

</section>

{% endblock %}