happypets/app/urls.py
from django.urls import path, include 
from .views import home, productos, contacto, comentarios, blog, agregar_producto, listar_productos, modificar_producto, eliminar_producto, registro, ProductoViewset, agregar_mascota, listar_mascota, modificar_mascota, eliminar_mascota, MascotaViewset
from rest_framework import routers

### ACUERDATE DE GUARDAR AQUI, EL PROGRAMA NO ESTA AVISANDO CUANDO NO GUARDAS AQUI Y ESTO NO PERMITE QUE SE EJECUTEN LOS VIEWS.


router = routers.DefaultRouter()
router.register('producto', ProductoViewset)
router.register('mascota', MascotaViewset)


urlpatterns = [
    path('', home, name="home"),
    path('productos/', productos, name="productos"),
    path('contacto/', contacto, name="contacto"),
    path('comentarios/', comentarios, name="comentarios"),
    path('blog/', blog, name="blog"),
    path('agregar-producto/', agregar_producto, name="agregar_producto"),
    path('agregar-mascota/', agregar_mascota, name="agregar_mascota"),
    path('listar-productos/', listar_productos, name="listar_productos"),
    path('listar-mascota/', listar_mascota, name="listar_mascota"),
    path('modificar-producto/<id>/', modificar_producto, name="modificar_productos"),
    path('modificar-mascota/<id>/', modificar_mascota, name="modificar_mascota"),
    path('eliminar-producto/<id>/', eliminar_producto, name="eliminar_producto"),
    path('eliminar-mascota/<id>/', eliminar_mascota, name="eliminar_mascota"),
    path('registro/', registro, name="registro"),
    path('api/', include(router.urls)),




]

happypets/happypets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

happypets/app/models.py
from django.db import models

# Create your models here.

class Producto(models.Model):
    nombre = models.CharField(max_length = 50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    fecha_duracion = models.DateField()

    def __str__(self):
        return self.nombre, self.precio, self.descripcion, self.fecha_duracion

    
class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    correo = models.EmailField()
    telefono = models.CharField(max_length=9)

    def __str__(self):
        return self.nombre, self.apellido, self.correo, self.telefono


class Mascota(models.Model):
    especie = models.CharField(max_length = 50)
    nombre = models.CharField(max_length = 50)
    descripcion = models.TextField()
    fecha_rescate = models.DateField()

    def __str__(self):
        return self.especie, self.nombre, self.descripcion, self.fecha_rescate

happypets/app/templates/app/producto/agregar.html
{% extends 'app/base.html' %}

{% load static %}

{% block contenido %}

<section id="Bienvenidos">
    <h2>AGREGAR OFERTAS DE PRODUCTOS A LA TIENDA</h2>
    <p>FORMULARIO PARA PODER AGREGAR OFERTAS DE PRODUCTOS A LA TIENDA PARA LOS CLIENTES</p>
</section>


        <div class="row">
            <div class="col-10 col-md-2 offset-md-4">

                <div class="card">
                    <div class="card-body">

                <form action="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}

                    {{ form }}

                    <br>
                    <br>
                    <div class="d-flex justify-content-center">

                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Guardar" class="btn btn-primary">

                    </div>
                </form>
                {{ mensaje }}
            </div>
        </div>
    </div>
</div>
<br>

<section id="info">
    <h3>FELICES HAPPY PETS</h3>
    <div class="contenedor">
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo1.jpg' %}" alt="">
            <h4>Los hermanos tom y luna con sus nuevos amigos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo2.jpg' %}" alt="">
            <h4>El serio luis con sus nuevos amigos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo3.jpg' %}" alt="">
            <h4>Chop encontro a su nuevo compañero</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo4.jpg' %}" alt="">
            <h4>Kira encontro a su nueva mejor amiga</h4>
        </div>

    </div>

</section>

{% endblock %}

happypets/app/templates/app/producto/listar.html
{% extends 'app/base.html' %}

{% load static %}

{% block contenido %}
<div class="card">
    <div class="card-body">
        <h2>Productos en ofeta</h2>
        <table class="table table-striped table-hover table-responsive-sm">
            <tr>
        
                <th>Nombre</th>
                <th>Precio</th>
                <th>Descripcion</th>
                <th>Fecha</th>
                <th>Opciones</th>
        
            </tr>
        
            {% for p in productos %}
        
            <tr>
                <td>{{ p.nombre | title }}</td>
                <td>${{ p.precio  }}</td>
                <td>{{ p.descripcion | title }}</td>
                <td>{{ p.fecha_duracion | title }}</td>
                <td>
                    {% if perms.app.change_producto %}
                    
                    <a href="{% url 'modificar_productos' p.id %}" class="btn btn-info">Modificar</a>
                    
                    {% endif %}

                    {% if perms.app.delete_producto %}
                    
                    <a href="{% url 'eliminar_producto' p.id %}" class="btn btn-danger">Eliminar</a>
                    
                    {% endif %}
                
                </td>
        
            </tr>
        
            {% endfor %}
        
        </table>
    </div>
</div>



<section id="info">
    <h3>FELICES HAPPY PETS</h3>
    <div class="contenedor">
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo1.jpg' %}" alt="">
            <h4>Los hermanos tom y luna con sus nuevos amigos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo2.jpg' %}" alt="">
            <h4>El serio luis con sus nuevos amigos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo3.jpg' %}" alt="">
            <h4>Chop encontro a su nuevo compañero</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo4.jpg' %}" alt="">
            <h4>Kira encontro a su nueva mejor amiga</h4>
        </div>

    </div>

</section>

{% endblock %}

happypets/app/templates/app/producto/modificar.html
{% extends 'app/base.html' %}

{% load static %}

{% block contenido %}

<section id="Bienvenidos">
    <h2>AGREGAR OFERTAS DE PRODUCTOS A LA TIENDA</h2>
    <p>FORMULARIO PARA PODER AGREGAR OFERTAS DE PRODUCTOS A LA TIENDA PARA LOS CLIENTES</p>
</section>


        <div class="row">
            <div class="col-10 col-md-2 offset-md-4">

                <div class="card">
                    <div class="card-body">

                <form action="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}

                    {{ form }}

                    <br>
                    <br>
                    <div class="d-flex justify-content-center">

                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Editar" class="btn btn-primary">

                    </div>
                </form>
                {{ mensaje }}
            </div>
        </div>
    </div>
</div>

<section id="info">
    <h3>FELICES HAPPY PETS</h3>
    <div class="contenedor">
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo1.jpg' %}" alt="">
            <h4>Los hermanos tom y luna con sus nuevos amigos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo2.jpg' %}" alt="">
            <h4>El serio luis con sus nuevos amigos</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo3.jpg' %}" alt="">
            <h4>Chop encontro a su nuevo compañero</h4>
        </div>
        <div class="info-productos">
            <img src="{% static 'app/img/BLOG/blog_abajo4.jpg' %}" alt="">
            <h4>Kira encontro a su nueva mejor amiga</h4>
        </div>

    </div>

</section>

{% endblock %}